### ISSUE TITLE
Add a way to change the `dir` prop in the `html` tag

### ISSUE THREAD

**Issue by yosefbeder** [rehypejs/rehype-document#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Can't add the `dir` prop to the `html` tag.

### Solution

It should be added directly in options like `language`.

### Alternatives

You can of course just add it to the stylesheet.

**Comment by wooorm** [comment]
Good idea. Can you work on it?

**Comment by wooorm** [comment]
@yosefbeder Are you interested in working on this?

**Comment by yosefbeder** [comment]
> @yosefbeder Are you interested in working on this?

Sorry i didn't see the first message

**Comment by yosefbeder** [comment]
> > @yosefbeder Are you interested in working on this?
> 
> Sorry i didn't see the first message

I am gonna try

**Comment by yosefbeder** [comment]
I will start working on it tomorrow
