### ISSUE TITLE
Read the document title from `file.data.title`

### ISSUE THREAD

**Issue by Delapouite** [rehypejs/rehype-document#14]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hi

Currently the title of the document is assigned like this:

```js
const title = options.title || file.stem
```

There are a few situations where this value, may have been extracted/computed upstream in the processor.

- by reading the `#+title:` keyword if starting from an Org document
- by looking at the unique `h1` element if starting from HTML document
- …

Therefore, it would be great if this plugin would also have a look at data aggregated on the `vfile`.

### Solution

If this is ok with you, I can prepare a PR with the following change and the associated documentation:

```js
const title = options.title || file.data.title || file.stem
```

Thanks.

### Alternatives

-

**Comment by wooorm** [comment]
Yeah, good idea I think.
rehype-meta supports this too: https://github.com/rehypejs/rehype-meta#title
It configures from file.data.meta:  https://github.com/rehypejs/rehype-meta#title 

This is also populated by https://github.com/rehypejs/rehype-infer-title-meta

So I think I'd prefer a little more privacy with file.data.meta, but otherwise good! 👍

**Comment by wooorm** [comment]
solved in https://github.com/rehypejs/rehype-document/releases/tag/7.0.0!
