### ISSUE TITLE
Allow custom meta tags

### ISSUE THREAD

**Issue by syzer** [rehypejs/rehype-document#5]
example:
options.meta = []

**Comment by wooorm** [comment]
Why would you want that?

**Comment by syzer** [comment]
You can use meta not only for view port and language, for example:
 - description
(old) https://yoast.com/meta-descriptions/
 - redirect,

**Comment by wooorm** [comment]
Yes I know, but what do *you* want to use this for?

**Comment by syzer** [comment]
Imagine you work for large company... that in company different department is responsible for contents other for meta/SEO and so on...
Example: redirects 302 are done from different departament... so only way to deliver feature is to a) change company structure b) use `meta` tag

I have use case now for meta = [{`description`:.... `name`:.....}]
But might be more ....

**Comment by syzer** [comment]
We could PR you, if that's a big problem to add this feature

**Comment by wooorm** [comment]
I get that! But I feel like you’re falling into the [XY](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) trap!

You can always [insert](https://github.com/syntax-tree/hast-util-select) meta elements through your own plugin!

**Comment by syzer** [comment]
:D I know. 
The XY is how big companies operate :D,
Was hoping I can use your doc plugin with `title, meta and css`... please?

**Comment by wooorm** [comment]
Well, it’s rather easy to do yourself:

```js
function plugin() {
  return transformer
}
function transformer(tree) {
  select('head', tree).children.push(
    h('meta', {name: 'foo', content: 'bar'}),
    h('meta', {name: 'baz', content: 'qux'})
  )
}
```

But if we’d add it here, I need more info on your usage, and how to implement it. Could you expand on what you *exactly* want to do, and why? And how you propose adding it?

P.S. title and css are supported already.

**Comment by syzer** [comment]
For API, I would use standard Array of structs, ex:

 .use(doc, {title: 'Hi!'}) => 
```js
 .use(doc, { 
   title: 'Hi!', 
   meta: [
     { name: 'foo', content: 'bar' },
     { name: 'baz', content: 'qux' }],
   css: '....',
   responsive: true // not sure here
})
``` 
Does that make sense ?

**Comment by syzer** [comment]
this `responsive` might have name collision with meta tags... but as a separate plugin also will have collision.

**Comment by wooorm** [comment]
* Could we use an object? `{foo: 'bar', baz: 'qux'}`?
* Could we just add a `head` option, that adds the given nodes (`[h('meta', {name: 'foo', content: 'bar'}), ...]`) to the end of the head?

**Comment by syzer** [comment]
First bullet: 
This idea to use object is good
so:
```js
{ description: 'Wir sind superb' name: `content` } 
```
would work, no?
Second bullet: I do not have opinion. (Implementation is secondary to nice API)

**Comment by wooorm** [comment]
* first point: yup
* second point: I feel this is good and extensible: you could add favicons and whatever too.

**Comment by syzer** [comment]
second point also would work for some head scripts and stuff like that...

**Comment by wooorm** [comment]
Yup! Would you be into working on a pr?

**Comment by wooorm** [comment]
I’d suggest a new `head` option that accepts a list of nodes?

**Comment by syzer** [comment]
I think the object API is better for users, so should have priority
, and `h( )` is more flexible so it could be exposed, too...
How 7th on June sounds?
Also I would like to drop semicolons and move to es2015, wdyt?

**Comment by wooorm** [comment]
Sure, relax! Take your time 🙂

I’d prefer just the `head` part, I think, that would work for your use case too, right?

And I just removed semicolons; I like prettier too. However, I’d rather not use esnext.

**Comment by syzer** [comment]
es2015, no esnext... deal ? 
What do you think about maybe using `babel` (for dev)to achive backward compatibility ?

**Comment by wooorm** [comment]
Ohh sorry, I didn‘t make myself clear. ernest IMO is es5 and later! I like everyone to be able to read and use the code, and I’d rather not add babel.

**Comment by wooorm** [comment]
@syzer Are you working on this? Anything I can help with?

**Comment by syzer** [comment]
Ah.. sorry... went on holidays.
We used react static head tag in the meantime. So our `html` is merge between `.md` and `javascript/web` component.

But I will work on it today :-D

**Comment by wooorm** [comment]
Don’t say sorry for holidays! They’re important! 👍

**Comment by wooorm** [comment]
Done!
